config/routes.rb
Finalproject::Application.routes.draw do

  devise_for :users , :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  root to: 'events#index'
  resources :events
  match '/events/new' , to: 'events#create' , via: :post
  post "data/event" => 'events#save'

end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :user
end

app/models/identity.rb
class Identity < ActiveRecord::Base 



belongs_to :user 
validates_presence_of :user_id, :uid, :provider
validates_uniqueness_of :uid, :scope => :provider

def self.find_for_oauth(auth) 
identity = find_by(provider: auth.provider, uid: auth.uid) 
	if identity.nil? 
	identity = create(uid: auth.uid, provider: auth.provider) 
	end 
identity 
end 

end 

app/models/user.rb
class User < ActiveRecord::Base

    has_many :events

TEMP_EMAIL = 'change@me.com'
  TEMP_EMAIL_REGEX = /change@me.com/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)
    user = identity.user
    if user.nil?

      # Get the existing user from email if the OAuth provider gives us an email
      user = User.where(:email => auth.info.email).first if auth.info.email

      # Create the user if it is a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: auth.info.email.blank? ? TEMP_EMAIL : auth.info.email,
          password: Devise.friendly_token[0,20]
        )
        #user.skip_confirmation!
        user.save!
      end

      # Associate the identity with the user if not already
      if identity.user != user
        identity.user = user
        identity.save!
      end
    end
    user
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  layout :layout_by_controller

  protected

  def layout_by_controller
  		devise_controller? ? 'devise' : 'application'
  	end
  	
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

def index
	@events = Event.all
end

def new
	@event = Event.new
end


def create
	@event = Event.new(event_params)
	
	if @event.save
		flash[:notice] = "Successfully created a new event"
		redirect_to events_path
	else 
		flash.now[:error] = "There was a problem"
		render "new"
	end	
end

  def save
    event = Event.new
    event.title = params[:title]
    event.start = params[:start]
    event.end = params[:end]
    event.allday =params[:allday]
    event.user = current_user
    event.save
    render text: "someString"
  end



private
def event_params
	params.require(:event).permit(:title, :color, :start, :end, :allday, :commit)
end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_oauth(env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/index.html.erb
<div class = "container">
	<div id="calendar"></div>
    <div id="events" style="display: none;">
      <% @events.each do |event| %>
      <div>
        <div class="start"><%= event.start.to_s %></div>
        <div class="end"><%= event.end.to_s %></div>
        <div class="title"><%= event.title %></div>
      </div>
      <% end %>
    </div>
</div>

app/views/events/new.html.erb
<div class="container">
	<%= form_for :event do |f| %>
  <div>
    <%= f.label :New_Event %>
    <%= f.text_field :title %>
  </div>
 
  <p>
    <%= f.label :Color %>
    <%= f.text_field :color %>
  </p>
 
 <p>
 	<%= f.label :Start %>
 	<%= f.datetime_field :start, class: "datetimepicker1", 'data-format' => 'yyyy-MM-dd HH:mm:ss' %>

 </p>

<p>
 	<%= f.label :End %>
 	<%= f.datetime_field :end, class: 'datetimepicker2', 'data-format' => 'yyyy-MM-dd HH:mm:ss' %>

  
 </p>

  <p> 
      <%= f.label :All_Day %>
      <%= f.check_box :allday %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', events_path %>
</div>

<script type="text/javascript">
  $(function(){
    $('.datetimepicker1 ,.datetimepicker2').datetimepicker({});
  });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalproject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


</head>
<body>
	<div class="row-fluid">   
		<div class="span10 offset1">
			<div class="container">     
				<div class="jumbotron text-center">       
					<h1>Calendar</h1> <br />      
						<p>Welcome! <strong><%= current_user.email %></strong> |
					<%= link_to 'logout', destroy_user_session_path, :method => 'delete' %>   
					 </p> 
				</div> 
				<%=  link_to 'Create New Event',events_new_path %>
			</div>  
	</div> 
</div> 

<%= yield %>
<br />
<div id="footer" class="container">
        <div class="navbar navbar-dafault">
            <div class="navbar-inner navbar-content-center">
            <p class="text-muted credit text-center"> Team Rocket | Thanh | Sean | Harry | Yuxin | Kate</p>
            </div>
        </div>
    </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalproject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row-fluid">   
		<div class="span10 offset1">
			<div class="container">     
				<div class="jumbotron text-center">       
					<h1>Calendar</h1>       
						<p>Welcome! </p>     
				</div> 
			</div>  
		</div> 
	</div> 
	<div class="row-fluid">
		<div class="span4 offset4 ">
			<%= yield %>
		</div>
	</div>
	</body>
</html>